language: csharp
solution: Collections.sln

before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore Collections.sln

after_script:
  - nunit-console CollectionsTest/bin/Release/CollectionsTest.dll